# NOTE: This example requires the following prerequisites before executing the jobs
# 1. Ensure spark-team-a name space exists
# 2. replace <ENTER_YOUR_BUCKET_NAME> with your bucket name

---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: tpcds-data-generation-3t
  namespace: spark-team-a
spec:
  type: Scala
  mode: cluster
  image: ghcr.io/aws-samples/emr-on-eks-benchmark:3.1.2
  imagePullPolicy: IfNotPresent
  sparkVersion: 3.1.2
  mainClass: com.amazonaws.eks.tpcds.DataGeneration
  mainApplicationFile: local:///opt/spark/examples/jars/eks-spark-benchmark-assembly-1.0.jar
  arguments:
    # TPC-DS data location
    - "s3a://<ENTER_YOUR_BUCKET_NAME>/TPCDS-TEST-3T"
    # Path to kit in the docker image
    - "/opt/tpcds-kit/tools"
    # Data Format
    - "parquet"
    # Scale factor (in GB)
    - "3000"
    # Generate data num partitions
    - "200"
    # Create the partitioned fact tables
    - "true"
    # Shuffle to get partitions coalesced into single files.
    - "true"
    # Logging set to WARN
    - "true"
  sparkConf:
    "spark.network.timeout": "2000s"
    "spark.executor.heartbeatInterval": "300s"
    "spark.kubernetes.memoryOverheadFactor": "0.3"
    "spark.sql.files.maxRecordsPerFile": "30000000"
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"

    # S3 settings
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version": "2"
    "spark.kubernetes.executor.podNamePrefix": "oss-data-gen"
    "spark.executor.defaultJavaOptions": "-verbose:gc -XX:+UseG1GC"
    "spark.driver.defaultJavaOptions": "-XX:+UseG1GC"

  restartPolicy:
    type: never
  volumes: # using NVMe instance storage mounted on /mnt/k8s-disks
    - name: spark-local-dir-1
      hostPath:
        path: /mnt/k8s-disks
        type: Directory
  driver:
    volumeMounts: # Points to InstanceStore NVMe SSD for shuffle spill over from memory
      - name: spark-local-dir-1
        mountPath: /data1
        readOnly: false
    initContainers:
      - name: volume-permissions
        image: public.ecr.aws/y4g4v0z7/busybox
        command: [ 'sh', '-c', 'chown -R 185 /mnt/k8s-disks' ]
        volumeMounts:
          - mountPath: "/mnt/k8s-disks"
            name: "spark-local-dir-1"
    cores: 10
    coreLimit: "10.1"
    memory: "10g"
    serviceAccount: spark-team-a
    nodeSelector:
      NodeGroupType: "SparkMemoryOptimized"
    tolerations:
      - key: "spark-memory-optimized"
        operator: "Exists"
        effect: "NoSchedule"
  executor:
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
        readOnly: false
    cores: 11
    coreLimit: "11.1"
    memory: "15g"
    # 3 executors per node 9 nodes
    instances: 26
    serviceAccount: spark-team-a
    nodeSelector:
      NodeGroupType: "SparkMemoryOptimized"
    tolerations:
      - key: "spark-memory-optimized"
        operator: "Exists"
        effect: "NoSchedule"
