# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: GitRepository
# metadata:
#   name: helloworld
#   namespace: flux-system
# spec:
#   secretRef:
#     name: github-token
#   interval: 60s
#   url: https://github.com/manabuOrg/test-terraform
#   ref:
#     branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
  namespace: flux-system
spec:
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: flux-system
  writeOutputsToSecret:
    name: my-output
